CC = g++
flags = -Wall

main: build/main.o build/sort.o build/source.o 
	$(CC) $(flags) -o main.exe build/main.o build/circle.o build/errors_circle.o 

build/main.o: main.cpp
	$(CC) -c $(flags) -o build/main.o main.cpp
	
build/sort.o: src/sort.cpp
	$(CC) -c $(flags) -o build/strings.o src/circle.cpp

build/source.o: src/source.cpp
	$(CC) -c $(flags) -o build/errors_catch.o src/.cpp
	


run:
	./main

cnr:
	make main
	make run


