CC = g++
flags = -Wall

main: build/main.o build/sort.o build/source.o 
	$(CC) $(flags) -o main.exe build/main.o build/circle.o build/errors_circle.o 

build/main.o: main.cpp
	$(CC) -c $(flags) -o build/main.o main.cpp
	
build/sort.o: src/sort.cpp
	$(CC) -c $(flags) -o build/sort.o src/sort.cpp

build/source.o: src/source.cpp
	$(CC) -c $(flags) -o build/source.o src/source.cpp


run:
	./main

cnr:
	make main
	make run


